# Generated by Django 5.1.3 on 2024-12-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_details',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Debit / Credit Card'), ('cod', 'Cash On Delivery')], default='upi', max_length=20),
        ),
    ]
