# Generated by Django 5.1.3 on 2024-12-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_state',
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
