# Generated by Django 5.1.3 on 2024-12-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_collection_slug_product_slug_alter_collection_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
    ]
