# Generated by Django 5.1.3 on 2024-12-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='updated_at',
        ),
    ]
