# Generated by Django 5.1.3 on 2024-12-03 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_orderline_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='orderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='current_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
