# Generated by Django 5.1.3 on 2024-12-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_collection_slug_remove_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_state',
        ),
    ]
