# Generated by Django 5.1.3 on 2024-12-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('regular', 'Regular'), ('express', 'Express')], default='regular', max_length=10),
        ),
    ]
