# Generated by Django 5.1.3 on 2024-12-04 08:59

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('read_time', models.PositiveIntegerField(default=0)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
