# Generated by Django 5.1.3 on 2024-12-04 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philatelist', '0003_remove_philatelist_wallet_balance'),
        ('services', '0004_blog_delete_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='philatelist.philatelist', null=True, blank=True),
            preserve_default=False,
        ),
    ]
