# Generated by Django 5.1.3 on 2024-12-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('philatelist', '0003_remove_philatelist_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.TextField(max_length=255)),
                ('main_office', models.TextField(max_length=100)),
                ('sub_division', models.TextField(max_length=100)),
                ('postal_code', models.TextField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('philatelist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='philatelist.philatelist')),
                ('postal_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.postaloffice')),
            ],
            options={
                'abstract': False,
            },
            bases=('philatelist.philatelist',),
        ),
    ]
