# Generated by Django 5.1.3 on 2024-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('Private', 'Private / Individual'), ('Dealer', 'Stamp Dealer / Shop'), ('Company', 'Company')], max_length=10)),
                ('name_of_applicant', models.CharField(max_length=100)),
                ('mailing_address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('gift_subscription_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gift_subscription_address', models.TextField(blank=True, null=True)),
                ('order_frequency', models.CharField(choices=[('Once a Year', 'Once a Year'), ('Twice a Year', 'Twice a Year'), ('Four Times a Year', 'Four Times a Year'), ('Six Times a Year', 'Six Times a Year')], max_length=20)),
                ('mint_commemorative_stamps', models.IntegerField(default=0)),
                ('mint_commemorative_stamps_no_personality', models.IntegerField(default=0)),
                ('mint_definitive_stamps', models.IntegerField(default=0)),
                ('top_marginal_block_of_4', models.IntegerField(default=0)),
                ('bottom_marginal_block_of_4', models.IntegerField(default=0)),
                ('full_sheet', models.IntegerField(default=0)),
                ('first_day_covers_stamped_cancelled', models.IntegerField(default=0)),
                ('first_day_covers_no_personality', models.IntegerField(default=0)),
                ('first_day_covers_blank', models.IntegerField(default=0)),
                ('information_brochure_stamped_cancelled', models.IntegerField(default=0)),
                ('information_brochure_blank', models.IntegerField(default=0)),
                ('annual_stamp_pack', models.IntegerField(default=0)),
                ('special_annual_stamp_pack_personalities', models.IntegerField(default=0)),
                ('childrens_special_stamp_pack', models.IntegerField(default=0)),
                ('special_collectors_stamp_pack', models.IntegerField(default=0)),
                ('first_day_cover_pack_thematic', models.IntegerField(default=0)),
                ('postal_stationery', models.IntegerField(default=0)),
                ('mini_sheets', models.IntegerField(default=0)),
                ('other_items', models.TextField(blank=True, null=True)),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('signature_of_applicant', models.ImageField(upload_to='signatures/')),
            ],
        ),
    ]
