# Generated by Django 5.1.3 on 2024-12-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pda',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='pda',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pda',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pda',
            name='signature_of_applicant',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
