# Generated by Django 5.1.3 on 2024-12-04 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pda_aadhar_card_pda_rejection_reason_pda_status_and_more'),
        ('philatelist', '0003_remove_philatelist_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='pda',
            name='philatelist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pda_applications', to='philatelist.philatelist'),
            preserve_default=False,
        ),
    ]
