# Generated by Django 5.1.3 on 2024-12-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_pda_philatelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postaloffice',
            name='sub_division',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
