# Generated by Django 5.1.3 on 2024-12-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_adminuser_is_super_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaloffice',
            name='alias',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postaloffice',
            name='main_office',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Kolkata', 'Kolkata'), ('Chennai', 'Chennai')], max_length=100),
        ),
        migrations.AlterField(
            model_name='postaloffice',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='postaloffice',
            name='sub_division',
            field=models.CharField(blank=True, choices=[('Borivali', 'Borivali'), ('Andheri', 'Andheri'), ('Ghatkopar', 'Ghatkopar'), ('Kurla', 'Kurla'), ('NCR', 'NCR')], max_length=100, null=True),
        ),
    ]
