# Generated by Django 5.1.3 on 2024-12-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_postaloffice_alias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalOfficeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Tamil Nadu', 'Tamil Nadu'), ('Anna Road HO', 'Anna Road HO'), ('Arakkonam Division', 'Arakkonam Division'), ('Chengalpattu Division', 'Chengalpattu Division'), ('Chennai City Central Division', 'Chennai City Central Division'), ('Chennai City North Division', 'Chennai City North Division'), ('Chennai City South Division', 'Chennai City South Division'), ('Chennai GPO', 'Chennai GPO'), ('Coimbatore Division', 'Coimbatore Division'), ('Cuddalore Division', 'Cuddalore Division'), ('Dharmapuri Division', 'Dharmapuri Division'), ('Dindigul Division', 'Dindigul Division'), ('Erode Division', 'Erode Division'), ('Kanchipuram Division', 'Kanchipuram Division'), ('Kanniyakumari Division', 'Kanniyakumari Division'), ('Karaikudi Division', 'Karaikudi Division'), ('Karur Division', 'Karur Division'), ('Kovilpatti Division', 'Kovilpatti Division'), ('Krishnagiri Division', 'Krishnagiri Division'), ('Kumbakonam Division', 'Kumbakonam Division'), ('Madurai Division', 'Madurai Division'), ('Mayiladuthurai Division', 'Mayiladuthurai Division'), ('Nagapattinam Division', 'Nagapattinam Division'), ('Namakkal Division', 'Namakkal Division'), ('Nilgiris Division', 'Nilgiris Division'), ('Pattukotai Division', 'Pattukotai Division'), ('Pollachi Division', 'Pollachi Division'), ('Pondicherry Division', 'Pondicherry Division'), ('Pudukottai Division', 'Pudukottai Division'), ('Ramanathapuram Division', 'Ramanathapuram Division'), ('Salem East Division', 'Salem East Division'), ('Salem West Division', 'Salem West Division'), ('Sivaganga Division', 'Sivaganga Division'), ('Srirangam Division', 'Srirangam Division'), ('Tambaram Division', 'Tambaram Division'), ('Thanjavur Division', 'Thanjavur Division'), ('Theni Division', 'Theni Division'), ('Tiruchirappalli Division', 'Tiruchirappalli Division'), ('Tirunelveli Division', 'Tirunelveli Division'), ('Tirupattur Division', 'Tirupattur Division'), ('Tirupur Division', 'Tirupur Division'), ('Tiruvannamalai Division', 'Tiruvannamalai Division'), ('Tuticorin Division', 'Tuticorin Division'), ('Vellore Division', 'Vellore Division'), ('Virudhunagar Division', 'Virudhunagar Division'), ('Vriddhachalam Division', 'Vriddhachalam Division'), ('Mumbai', 'Mumbai'), ('Andheri East S.O', 'Andheri East S.O'), ('Andheri H.O', 'Andheri H.O'), ('Andheri Railway Station S.O', 'Andheri Railway Station S.O'), ('Antop Hill S.O', 'Antop Hill S.O'), ('Azad Nagar S.O', 'Azad Nagar S.O'), ('Bandra West S.O', 'Bandra West S.O'), ('Bandra(East) S.O', 'Bandra(East) S.O'), ('Bhandup West S.O', 'Bhandup West S.O'), ('Borivali East S.O', 'Borivali East S.O'), ('Borivali H.O', 'Borivali H.O'), ('Borivali West S.O', 'Borivali West S.O'), ('Chakala Midc S.O', 'Chakala Midc S.O'), ('Chembur H.O', 'Chembur H.O'), ('Chinchbunder S.O', 'Chinchbunder S.O'), ('Colaba S.O', 'Colaba S.O'), ('Dadar H.O', 'Dadar H.O'), ('Dahisar S.O', 'Dahisar S.O'), ('Dharavi S.O', 'Dharavi S.O'), ('FCI S.O', 'FCI S.O'), ('Ghatkopar West S.O', 'Ghatkopar West S.O'), ('Girgaon S.O', 'Girgaon S.O'), ('Goregaon East S.O', 'Goregaon East S.O'), ('Goregaon RS S.O', 'Goregaon RS S.O'), ('Grant Road S.O', 'Grant Road S.O'), ('Jacob Circle S.O', 'Jacob Circle S.O'), ('Kalbadevi H.O', 'Kalbadevi H.O'), ('Kandivali East S.O', 'Kandivali East S.O'), ('Kandivali West S.O', 'Kandivali West S.O'), ('Kurla West S.O', 'Kurla West S.O'), ('Mahim Bazar S.O', 'Mahim Bazar S.O'), ('Mahim H.O', 'Mahim H.O'), ('Malad East S.O', 'Malad East S.O'), ('Malad S.O', 'Malad S.O'), ('Mandvi S.O', 'Mandvi S.O'), ('Matunga S.O', 'Matunga S.O'), ('Mulund West S.O', 'Mulund West S.O'), ('Mumbai Central H.O', 'Mumbai Central H.O'), ('Pant Nagar S.O', 'Pant Nagar S.O'), ('Parel Naka S.O', 'Parel Naka S.O'), ('Parel S.O', 'Parel S.O'), ('Rajawadi S.O', 'Rajawadi S.O'), ('Ranade Road S.O', 'Ranade Road S.O'), ('Santacruz(East) S.O', 'Santacruz(East) S.O'), ('Sewri S.O', 'Sewri S.O'), ('Sion S.O', 'Sion S.O'), ('Tagore Nagar S.O', 'Tagore Nagar S.O'), ('Tank Road S.O', 'Tank Road S.O'), ('Tilak Nagar S.O', 'Tilak Nagar S.O'), ('V J B Udyan S.O', 'V J B Udyan S.O'), ('Vileparle Railway Station S.O', 'Vileparle Railway Station S.O'), ('Vileparle(West) S.O', 'Vileparle(West) S.O'), ('Wadala S.O', 'Wadala S.O')], max_length=255, null=True)),
                ('is_main_office', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_offices', to='dashboard.postalofficereference')),
            ],
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='postal_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.postalofficereference'),
        ),
        migrations.DeleteModel(
            name='PostalOffice',
        ),
    ]
