# Generated by Django 5.1.3 on 2024-12-07 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dak_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproduct',
            name='slug',
            field=models.SlugField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangeproduct',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ExchangeProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dak_exchange/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='dak_exchange.exchangeproduct')),
            ],
        ),
    ]
