# Generated by Django 5.1.3 on 2024-12-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philatelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='philatelist',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
