# Generated by Django 5.1.3 on 2024-12-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philatelist', '0002_philatelist_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='philatelist',
            name='wallet_balance',
        ),
    ]
