# Generated by Django 5.1.3 on 2024-12-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philatelist', '0003_remove_philatelist_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='philatelist',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
